// Video data from the Excel file
const videoData = [
    {        serial: 1,
        taskId: 2466,
        title: "Overview of Web development",
        driveLink: "https://drive.google.com/file/d/11PbHiz5fNCUN1C8XDliPaPLQxpcAR-sU/view?usp=sharing",
        description: "What is web development. Tools and languages used in Web Development",
        category: "fundamentals"
    },
    {        serial: 2,
        taskId: 2481,
        title: "Introduction to version control system",
        driveLink: "https://drive.google.com/file/d/1lg1GgonXldPHUcC_aRIClqZUXOE7_O7t/view?usp=sharing",
        description: "Setting up account on GitHub. Difference between git and github",
        category: "fundamentals"
    },
    {        serial: 3,
        taskId: 2486,
        title: "What is Git. Connecting Git on vs code",
        driveLink: "https://drive.google.com/file/d/1bNAeHcnpzcdHQrK8OfDdCIrihD2IZDbC/view?usp=sharing",
        description: "Downloading and installing git and vs code.",
        category: "fundamentals"
    },
    {        serial: 4,
        taskId: 2491,
        title: "SDLC",
        driveLink: "https://drive.google.com/file/d/11wM7MzD2XuwuJqou672XM7GKrWD12YQF/view?usp=sharing",
        description: "What is SDLC. Understanging different stages of SDLC",
        category: "fundamentals"
    },
    {        serial: 5,
        taskId: 2496,
        title: "What is React",
        driveLink: "https://drive.google.com/file/d/1EVp6SwiTn5ZarvhFuO--WtXbvIbBKFrc/view?usp=sharing",
        description: "Understanding the Basic concept of JavaScript and some of it's framework",
        category: "fundamentals"
    },
    {        serial: 6,
        taskId: 2658,
        title: "Formatting tags in HTML",
        driveLink: "https://drive.google.com/file/d/1zS6Uwvn_qr6zyuIg0aduezf2xjtxKCgn/view?usp=drive_web",
        description: "Learn HTML formatting tags including paragraphs, blockquotes, small tags, subscript and superscript.",
        category: "html"
    },
    {        serial: 7,
        taskId: 2663,
        title: "How to create tables in HTML document",
        driveLink: "https://drive.google.com/file/d/1qobKc6llwDxtZxLfwQmbXJLEs5Egrow_/view?usp=sharing",
        description: "Create HTML tables with headers, rows, and borders. Learn table structure and attributes.",
        category: "html"
    },
    {        serial: 8,
        taskId: 2668,
        title: "Different types of lists",
        driveLink: "https://drive.google.com/file/d/1qaQvf4uqzg-KIpt3mKnh5z1GvPZylpaE/view",
        description: "Learn ordered and unordered lists in HTML with different numbering styles including Roman numerals.",
        category: "html"
    },
    {        serial: 9,
        taskId: 2673,
        title: "Introduction to iFrames",
        driveLink: "https://drive.google.com/file/d/1_7_Q5Q16QEkpmIx3PzzOH25cCvA6SxMc/view?usp=sharing",
        description: "Embed external websites and content using iframes. Learn iframe sizing and alignment.",
        category: "html"
    },
    {        serial: 10,
        taskId: 2678,
        title: "Adding audio and video files to html document",
        driveLink: "https://drive.google.com/file/d/1ybmK6vFh6qG-7YVwBrGqOap1XwzH8iJM/view?usp=sharing",
        description: "Add video and audio elements to HTML with multiple source formats and fallback content.",
        category: "html"
    },
    {        serial: 11,
        taskId: 2924,
        title: "Basic tags",
        driveLink: "https://drive.google.com/file/d/1zS6Uwvn_qr6zyuIg0aduezf2xjtxKCgn/view?usp=drive_web",
        description: "Master fundamental HTML tags including paragraphs, blockquotes, and text formatting.",
        category: "html"
    },
    {        serial: 12,
        taskId: 2939,
        title: "Lists In HTML",
        driveLink: "https://drive.google.com/file/d/1qobKc6llwDxtZxLfwQmbXJLEs5Egrow_/view?usp=sharing",
        description: "Create ordered and unordered lists with custom styling and numbering formats.",
        category: "html"
    },
    {        serial: 13,
        taskId: 2945,
        title: "Representation of data in tabular format",
        driveLink: "https://drive.google.com/file/d/1qaQvf4uqzg-KIpt3mKnh5z1GvPZylpaE/view?usp=sharing",
        description: "Design forms and tables with merged cells using rowspan and colspan attributes.",
        category: "html"
    },
    {        serial: 14,
        taskId: 2951,
        title: "Embedding Multi-media files",
        driveLink: "https://drive.google.com/file/d/1d5IZbecH8qCMNhTWWSP6gSqtoPcvw2vI/view?usp=sharing",
        description: "Embed multimedia files with proper controls and multiple format support for compatibility.",
        category: "html"
    },
    {        serial: 15,
        taskId: 2957,
        title: "iFrames",
        driveLink: "https://drive.google.com/file/d/1_7_Q5Q16QEkpmIx3PzzOH25cCvA6SxMc/view?usp=sharing",
        description: "Embed PDF files and external documents using iframes with scrolling and resizing.",
        category: "html"
    },
    {        serial: 16,
        taskId: 2993,
        title: "Different ways to implement CSS in a HTML document",
        driveLink: "https://drive.google.com/file/d/1ybmK6vFh6qG-7YVwBrGqOap1XwzH8iJM/view?usp=sharing",
        description: "Create a HTML file. Create a style.css file. Connect the external CSS file to the HTML file. Remove the default CSS. Add an Image in the background.",
        category: "css"
    },
    {        serial: 17,
        taskId: 2999,
        title: "How to select a particular element in CSS",
        driveLink: "https://drive.google.com/file/d/1e_tWDOjQA-I11O_DVVRFaH7AGaaKzJRQ/view?usp=sharing",
        description: "Create a div with 2 paragraphs inside and 1 outside. Change the background color to light blue for paragraphs inside the div.",
        category: "css"
    },
    {        serial: 18,
        taskId: 3035,
        title: "Understanding the different values of border property",
        driveLink: "https://drive.google.com/file/d/12_EBwdFELSD-AoyeLuPReuhmIfHMrEe-/view?usp=sharing",
        description: "Design a container with multiple elements inside (at least 7). Set the border of the container to be 2px thick and solid.",
        category: "css"
    },
    {        serial: 19,
        taskId: 3041,
        title: "Changing the default color of hyperlinks",
        driveLink: "https://drive.google.com/file/d/18uY4VeCHpPJYEI1YN4J3wzCMB8iBuHzs/view?usp=sharing",
        description: "Create a list of links on a webpage and set their color to blue. When a user hovers over any of the links, change the color to green.",
        category: "css"
    },
    {        serial: 20,
        taskId: 3068,
        title: "Decorating text",
        driveLink: "https://drive.google.com/file/d/1-LG2EeHFzGKVTdCRJqcaZhdaa5ZBaVVb/view?usp=sharing",
        description: "Create a CSS rule for a paragraph with the class text-style: center-aligned, 18px font-size, bold and italic, 2px letter spacing.",
        category: "css"
    },
    {        serial: 21,
        taskId: 3074,
        title: "Block, Inline, and Inline-Block",
        driveLink: "https://drive.google.com/file/d/1aGSaaAjbEtP3TspN6HJPfFYa5DHpHYHo/view?usp=sharing",
        description: "Modify the CSS of three elements to demonstrate different display properties: block, inline, and inline-block.",
        category: "css"
    },
    {        serial: 22,
        taskId: 3080,
        title: "Smooth Button Hover Effect",
        driveLink: "https://drive.google.com/file/d/1jmnDLxknGbVq_3oD9ywJJfFIFIVoiGJ3/view?usp=sharing",
        description: "Create a button that smoothly changes its background to dark green and text color to black on hover with a 0.5s transition.",
        category: "css"
    },
    {        serial: 23,
        taskId: 3088,
        title: "Create a Basic Grid Layout",
        driveLink: "https://drive.google.com/file/d/1xrAlUYon7jXp-mq-b0ErvMKTeNlsZ6cN/view?usp=sharing",
        description: "Design a three-column layout inside a container with 900px width, equal-width columns, and 10px gap between columns.",
        category: "css"
    },
    {        serial: 24,
        taskId: 3094,
        title: "Breadcrumb Navigation",
        driveLink: "https://drive.google.com/file/d/1LpnalPR1pjJ0navDRLGIlp1jebMh1zEI/view?usp=sharing",
        description: "Create a breadcrumb navigation: Home > Blog > Web Development > HTML Basics. Use Bootstrap classes to style the breadcrumbs.",
        category: "css"
    },
    {        serial: 25,
        taskId: 3265,
        title: "Two Column Layout with Sidebar",
        driveLink: "https://drive.google.com/file/d/1GIrCzQ_SOxYt2XGKm-eA6eQ-hjqETe5K/view?usp=sharing",
        description: "Design a webpage layout: main content (75% width) and sidebar (25% width). On small screens, sidebar moves below main content.",
        category: "css"
    },
    {        serial: 26,
        taskId: 3281,
        title: "Different ways to implement JS",
        driveLink: "https://drive.google.com/file/d/1HkLkI4mW0ucGBbGR68cdPaldG3JsNqM0/view?usp=sharing",
        description: "Demonstrate three different ways to add JavaScript to a web page: inline, internal, and external JavaScript.",
        category: "javascript"
    },
    {        serial: 27,
        taskId: 3287,
        title: "Data types in JS",
        driveLink: "https://drive.google.com/file/d/1mulGHIfBm0I6Xqo-LHI-gDBb2Bzi5kcw/view?usp=sharing",
        description: "Create a JavaScript program with different data types: number, string, boolean, object, and array. Use typeof to display data types.",
        category: "javascript"
    },
    {        serial: 28,
        taskId: 3293,
        title: "Logical operators",
        driveLink: "https://drive.google.com/file/d/1OyMhHnEcHglFD9bpXkts6Cotk9K2RP3j/view?usp=sharing",
        description: "Create a JavaScript program using logical AND, OR, and NOT operators. Implement a login system with username and password validation.",
        category: "javascript"
    },
    {        serial: 29,
        taskId: 3299,
        title: "Using For Loop to Perform Repetitive Tasks in JavaScript",
        driveLink: "https://drive.google.com/file/d/1NqCAXZJ-vsPQmX4xhCM6fZukGXkQpvfl/view?usp=sharing",
        description: "Create a JavaScript program using for loops: print numbers 1-50, iterate arrays, generate Fibonacci sequence, create multiplication table.",
        category: "javascript"
    },
    {        serial: 30,
        taskId: 3305,
        title: "Using Object Methods to Manage a Shopping Cart",
        driveLink: "https://drive.google.com/file/d/1g9sKrH00Jkj_rnkF7uuJT1JDLGg3wcmP/view?usp=sharing",
        description: "Create a JavaScript shopping cart with methods to add items, remove items, calculate total price, and apply discounts.",
        category: "javascript"
    },
    {        serial: 31,
        taskId: 3323,
        title: "Implementing a To-Do List Using Array Methods",
        driveLink: "https://drive.google.com/file/d/14w2l_5yMaaefsDNS0ImdeGHLOwtWJuXE/view?usp=sharing",
        description: "Create a to-do list with functions to add, remove, mark as completed, display tasks, and sort tasks by completion status.",
        category: "javascript"
    },
    {        serial: 32,
        taskId: 3329,
        title: "Working with Map in JavaScript",
        driveLink: "https://drive.google.com/file/d/190CdnkAU_VI_-_eI50WtYxBPknGnPp9C/view?usp=sharing",
        description: "Create a map with key-value pairs, add entries, retrieve values, delete entries, and iterate using for...of loop.",
        category: "javascript"
    },
    {        serial: 33,
        taskId: 3335,
        title: "Extracting Numbers from a String Using RegEx with the Case-Insensitive Modifier",
        driveLink: "https://drive.google.com/file/d/1vSrZzIJCZeBUKxZ9eOOG3xda_TN5P86C/view?usp=sharing",
        description: "Create a string with letters and numbers. Write regex to find all numbers, extract and store in array.",
        category: "javascript"
    },
    {        serial: 34,
        taskId: 3341,
        title: "Creating a Form and Validating Required Fields",
        driveLink: "https://drive.google.com/file/d/1W911f_6ig3p29tznLWG2MetfUHRgndfi/view?usp=sharing",
        description: "Create an HTML form with Username and Email fields. Validate required fields, display error messages, and handle form submission.",
        category: "javascript"
    },
    {        serial: 35,
        taskId: 3347,
        title: "Using setTimeout to Demonstrate Asynchronous Behavior",
        driveLink: "https://drive.google.com/file/d/1463x1O_Yhrb-6pbztUb4dU70gi4j_v7-/view?usp=sharing",
        description: "Write a JavaScript program using setTimeout with a 3-second delay. Understand asynchronous execution order.",
        category: "javascript"
    },
    {        serial: 36,
        taskId: 3353,
        title: "Styling the Landing Page Using CSS",
        driveLink: "https://drive.google.com/file/d/13KEJK6csSie4B7Zt741ZK5nwv-BOAorQ/view?usp=sharing",
        description: "Apply modern typography, dark-themed color scheme, flexbox/grid layout, sticky navigation, and hover effects.",
        category: "css"
    },
    {        serial: 37,
        taskId: 3359,
        title: "Getting Started with React-Redux and Redux Toolkit",
        driveLink: "https://drive.google.com/file/d/11xzOWmkYG4u7pPwuZk-wDDE7mH263qus/view?usp=sharing",
        description: "Introduction to integrating Redux with React. Set up Redux store, create slices using Redux Toolkit, and connect with React components.",
        category: "react"
    },
    {        serial: 38,
        taskId: 3365,
        title: "Node.js Project Architecture: Best Practices for Beginners",
        driveLink: "https://drive.google.com/file/d/1eESV7VLD4UBvDSIqcfGvWdueTzaP8_Np/view?usp=sharing",
        description: "Explore well-organized Node.js project structure following industry best practices for maintainability and scalability.",
        category: "nodejs"
    },
    {        serial: 39,
        taskId: 3599,
        title: "What is node",
        driveLink: "https://drive.google.com/file/d/15MtssgVman5FB2NiwL9wgk3sty3MyZs9/view?usp=sharing",
        description: "Downloading and installing node. Understanding the Importance of node.",
        category: "nodejs"
    },
    {        serial: 40,
        taskId: 3605,
        title: "Components in React",
        driveLink: "https://drive.google.com/file/d/1kJou20ko2UV6amgqPYMfocRzy-x_oZQd/view?usp=sharing",
        description: "Create reusable ProfileCard components that take props like name, image, and description.",
        category: "react"
    },
    {        serial: 41,
        taskId: 3642,
        title: "Input Field with Live Preview",
        driveLink: "https://drive.google.com/file/d/1QBtIxcB9IvbrAI94b_vBiEchABzNnwp8/view?usp=sharing",
        description: "Build an input field where users can type text, and the text is displayed live below it using onChange and state.",
        category: "react"
    },
    {        serial: 42,
        taskId: 3648,
        title: "Product Display with Dynamic Props",
        driveLink: "https://drive.google.com/file/d/1F1uasBf84rjAL6iiSoNpvhgxvXe9a8sF/view?usp=sharing",
        description: "Build a Product component that accepts title, price, and availability as props. Display in a styled card with conditional rendering.",
        category: "react"
    },
    {        serial: 43,
        taskId: 3654,
        title: "Dynamic Route with Parameters",
        driveLink: "https://drive.google.com/file/d/1PeaAVyp5GezXXpj9u2BUxym5ONUPREIP/view?usp=sharing",
        description: "Build a UserProfile component with dynamic :userId route. Use useParams to access userId and simulate user data loading.",
        category: "react"
    },
    {        serial: 44,
        taskId: 3660,
        title: "useEffect for Fetching Data",
        driveLink: "https://drive.google.com/file/d/1bQAVgUSO6gV0cHwRmjER37ZRqPgVy1le/view?usp=sharing",
        description: "Build a component that fetches data from a public API on mount. Use useEffect, show loading state, and handle errors.",
        category: "react"
    }
];

// Category names mapping
const categoryNames = {
    fundamentals: "Web Dev Fundamentals",
    html: "HTML",
    css: "CSS",
    javascript: "JavaScript",
    react: "React",
    nodejs: "Node.js"
};
